name: Auto Release

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]
    paths:
      - "package.json"

jobs:
  generator:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    steps:
      - run: echo "The head of this PR starts with 'release/'"
      - run: echo ${{ github.event }}
      - uses: actions/checkout@v3
      - uses: 94dreamer/auto-release@develop
        id: changlog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.changlog.outputs.changlog }}
