name: Auto Release

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, closed]
    paths:
      - "package.json"
  issue_comment:
    types: [created, edited]

jobs:
  generator:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.merged == false &&
      startsWith(github.head_ref, 'release/')
    steps:
      - run: echo "The head of this PR starts with 'release/'"
      - uses: actions/checkout@v3
      - uses: 94dreamer/auto-release@develop
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
  comment_add_log:
    runs-on: ubuntu-latest
    if: >
      github.event.issue.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      github.event.issue.pull_request.head.base == 'develop' &&
      startsWith(github.event.issue.pull_request.head.ref, 'release/')
    steps:
      - run: echo ${{ github.event.issue.event_name }}
      - run: echo ${{ github.event.issue.pull_request.head.base }}
      - run: echo ${{ github.event.issue.pull_request.head.ref }}
      - run: echo pr_add_log $NUMBER
  merge_tag:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'release/')
    steps:
      - run: echo pr_merge_tag
